name: build

on:
    push:
        branches: [develop, main]
    pull_request:
        branches: [develop, main]
    workflow_dispatch:

jobs:
    pre-flight:
        strategy:
            matrix:
                python-version: ['3.10', '3.11']
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            # Install poetry
            - name: Install poetry
              run: pipx install poetry

            # Setup Python
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  cache: 'poetry'
                  python-version: ${{ matrix.python-version }}

            # Cache pre-commit
            - uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.cache/pre-commit-${{ matrix.python-version }}
                  key: pre-commit|${{ matrix.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

            # Install dependencies
            - name: Install dependencies
              run: |
                  poetry install --with dev,test --all-extras

            # Lint project using pre-commit config
            - name: Lint with pre-commit
              run: |
                  poetry run pre-commit --version
                  poetry run pre-commit install
                  poetry run pre-commit run --all-files
              env:
                  PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit-${{ matrix.python-version }}

    test:
        needs: pre-flight
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # os: [ubuntu-latest, macos-latest, windows-latest]
                os: [ubuntu-latest]
                python-version: ['3.10', '3.11']

        services:
            memcached:
                image: memcached
                ports:
                    - 11211:11211
            redis:
                image: redis
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v3

            # Install poetry
            - name: Install poetry
              run: pipx install poetry

            # Setup Python
            - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  cache: 'poetry'
                  python-version: ${{ matrix.python-version }}

            # Install dependencies
            - name: Install dependencies
              run: |
                  poetry install --with dev,test --all-extras

            # Test package and save artifacts
            - name: Test with pytest
              run: >
                  poetry run pytest
                  --cov=falcon_provider_cache
                  --cov-report=html:artifacts/cov-report-${{ matrix.os }}-${{ matrix.python-version }}
                  --cov-report=xml
                  --html=artifacts/test-report-${{ matrix.os }}-${{ matrix.python-version }}.html
                  --junitxml=junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml
                  --self-contained-html
                  tests/

            # Upload file to codecov
            - name: Upload to codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
                  # files: ./coverage1.xml,./coverage2.xml # optional
                  flags: pytest # optional
                  verbose: false # optional (default = false)

            # Artifact upload
            - name: Upload pytest test results
              uses: actions/upload-artifact@v3
              with:
                  name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
                  path: |
                      artifacts/cov-report-${{ matrix.os }}-${{ matrix.python-version }}
                      artifacts/test-report-${{ matrix.os }}-${{ matrix.python-version }}.html
                      junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml
              if: ${{ always() }}
